Create registration and user profile endpoint
InventorsDev/Team-Raspberry pull request #12
Opened 2023-07-18 12:24 UTC by Unique-01

Fixes part of #4 
This includes registration for student account only, email verification, password change, password reset, and profile

2023-07-20 21:18 UTC, Unique-01 commented
> Fixes part of #4 This includes registration for student account only, email verification, password change, password reset, and profile

Added new endpoints for content creator registration and also admin approval for the account

2023-07-25 21:30 UTC, leehomeecky commented
pleas stop trying to merge PR's that hasn't been reviewed.

2023-07-25 21:48 UTC, leehomeecky commented on backend/accounts/templates/email_verification.html
> +    <p><a href="{{ verification_url }}">{{ verification_url }}</a></p>
change `<p><a href="{{ verification_url }}">{{ verification_url }}</a></p>` to `<p><a href="{{ verification_url }}">verify</a></p>`

or something better

2023-07-25 21:48 UTC, leehomeecky commented on backend/accounts/views.py
> +            return Response({'detail': 'Invalid token.'}, status=status.HTTP_400_BAD_REQUEST)
the status code should be 403, un authorized

2023-07-25 21:48 UTC, leehomeecky commented on backend/accounts/views.py
> +            return Response({'detail': 'Invalid token.'}, status=status.HTTP_400_BAD_REQUEST)
status code should be 403, un authorized

2023-07-25 21:48 UTC, leehomeecky commented on backend/accounts/views.py
> +            return Response({'detail': 'Invalid token.'}, status=status.HTTP_400_BAD_REQUEST)
try refactor this, and let the error come once

2023-08-02 17:41 UTC, Odamola6 requested changes

2023-08-02 22:52 UTC, Odamola6 requested changes

2023-08-02 22:52 UTC, Odamola6 commented on backend/accounts/views.py
> +        return Response({'detail': 'Account activated successful.'})
This hasn't been changed yet

2023-08-02 23:00 UTC, Unique-01 commented on backend/accounts/views.py
> +        return Response({'detail': 'Account activated successful.'})
That is just the response sent to the front end

2023-08-03 17:33 UTC, Odamola6 approved these changes

2023-08-03 21:05 UTC, merged